Some spelling fixes
Sysinternals/ProcDump-for-Linux pull request #106
Opened 2020-12-09 22:28 UTC by aweeraman

2021-05-13 08:16 UTC, jahabibi approved these changes

2021-05-13 08:18 UTC, jahabibi requested changes

2021-05-13 08:18 UTC, jahabibi commented on src/ProcDumpConfiguration.c.orig
> +// Copyright (c) Microsoft Corporation. All rights reserved.
This file looks to have been committed in error. Please remove it and I can push these fixes through.

2021-05-13 08:25 UTC, aweeraman commented on src/ProcDumpConfiguration.c.orig
> +// Copyright (c) Microsoft Corporation. All rights reserved.
Thanks for the catch. It's done.

2021-06-19 00:37 UTC, jahabibi approved these changes

2021-06-19 00:37 UTC, merged